### ISSUE TITLE
Update package.json to point at the latest grunt-contrib-compress

### ISSUE THREAD

**Issue by sedge** [mozilla/brackets#215]
This is pending an upstream merge of [this PR](https://github.com/gruntjs/grunt-contrib-compress/pull/149)

**Comment by humphd** [comment]
@sedge that PR has been closed now, can you see if we can do this?

**Comment by sedge** [comment]
It's an illusion: https://github.com/gruntjs/grunt-contrib-compress/pull/152

**Comment by sedge** [comment]
@humphd @gideonthomas: The upstream patch blocking this has been merged.

**Comment by gideonthomas** [comment]
Thanks @sedge. Not sure if we want to take this patch in. Will come back to it later.

**Comment by humphd** [comment]
Fixed with #588
