### ISSUE TITLE
Leverage the LESS parser in the CSSRewriter

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/brackets#252]
We currently use our own parsing mechanisms and regexes to parse and rewrite CSS. However, we should probably use the LESS parser that brackets provides [here](https://github.com/adobe/brackets/blob/77e5509c0483508dc19072b44ddb58cc56135c2e/src/index.html#L50) instead so that we run into fewer parsing bugs.

**Comment by humphd** [comment]
The LESS version used in Brackets is older than the new docs.  We have to use `less.parser` and `.toCSS()`.  See https://github.com/adobe/brackets/blob/04efd92ae3d91ea70c6481a7e32e6e4f41676d55/src/utils/ExtensionUtils.js#L121-L131 for an idea of how to call the parser.  I'm not sure how you pass a custom plugin so it will let us rewrite image URLs.  See https://github.com/less/less-plugin-inline-urls/blob/master/lib/inline-images.js for some idea on how it *might* be done.

cc @Pomax.

**Comment by humphd** [comment]
It looks to me like Plugins were added in Less v2, so this might be tricky without also updating Less.

**Comment by humphd** [comment]
Maybe http://stackoverflow.com/questions/26607819/remove-properties-from-rendered-less-css/26610628#26610628 provides a way?

**Comment by Pomax** [comment]
small note: LESS<2 is incompatible with node v12, so you're going to want to update LESS regardless, if you want to keep the project runnable for people on the current version of Node

**Comment by humphd** [comment]
Looks like LESS v2.3.1 is coming upstream in the 1.4 milestone.

**Comment by humphd** [comment]
We no longer ship LESS in production (for size/perf savings), so closing this.
