### ISSUE TITLE
Improve startup experience

### ISSUE THREAD

**Issue by humphd** [mozilla/brackets#332]
It takes too long to get Bramble started.  Depending on the connection and browser, you can have a long period with no content (white page while a ton of CSS loads, blocking rendering), then a bunch of churn for extension loading, where we alter the UI.  We can do a lot better.

I'd like for us to tackle this problem on two fronts:
- actual startup performance
- perceived startup performance through UI/UX work

For the first one, https://www.youtube.com/watch?v=d5_6yHixpsQ&feature=youtu.be has some really interesting ideas for us to try, especially about adding an initial, static render.

I suspect that this will involve ongoing work and fixes, and won't all get done in a single bug.  This is similar too, and tightly related to our goal of staying as small as possible.

**Comment by humphd** [comment]
NOTE: despite my great love for the idea of `ServiceWorkers`, I don't think it's time to bother yet http://caniuse.com/#feat=serviceworkers

**Comment by JordanTheriault** [comment]
This could be converted into an ongoing milestone where we set particular timing goals. That video by Google is very informative and we can turn specific fixed into issues.

**Comment by humphd** [comment]
This is basically fixed.
