### ISSUE TITLE
keydown/up event.preventDefault is not getting respected

### ISSUE THREAD

**Issue by Pomax** [mozilla/brackets#431]
if I have code that acts on keydown/keyup and calls preventDefault() for both, then activate those in the preview window by for instance pressing and holding space, the brackets editor will suddenly start typing a million space characters.

This is particularly destructive for UI that uses things like space for "drag things around instead of drawing". One moment you're testing your UI, the next you're trying to undo the damage brackets did to your source, which caused a reload of the preview, at which point _everything_ blows up.

**Comment by Cryzek** [comment]
@Pomax Does this -  "activate those in the preview window by for instance pressing and holding space" mean triggering the events in the preview window?
I added an eventListener on document for keydown events, and did a event.preventDefault() for space key. Worked fine for me.

**Comment by Pomax** [comment]
I have no idea what I ran into anymore, to be honest. It's entirely likely this is for a version of our brackets that isn't even remotely related to what is in the repo almost two and a half years later... I'll close this =)
