### ISSUE TITLE
Files with spaces can make the browser tab hang

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/brackets#437]
STR:
- Create a CSS file with spaces in the name
- Add a style rule (I tried an `h1` rule)
- Go to the `index.html` doc and link to the newly created stylesheet
- Go back to the stylesheet and try to add a space after an opening brace (I think any sort of change would also cause the same thing)

Result:
The tab hangs and then we see a bunch of errors pop up in the console...after which the tab still hangs (I had to shut it down with chrome task manager).

Here's a gif of what I did for this:
![spaces-breaks-everything](https://cloud.githubusercontent.com/assets/5816130/9392964/5c677028-474d-11e5-82cf-40302e494137.gif)

I tried this with a file without spaces in the name and couldn't reproduce.

**Comment by humphd** [comment]
Fixed with #588
