### ISSUE TITLE
can't "copy", "cut", or "paste" via the context menu

### ISSUE THREAD

**Issue by Pomax** [mozilla/brackets#451]
For some reason the Brackets context menu has copy/cut/paste disabled (or not even there at all?). That's a big problem for devs, let alone learners =)

**Comment by humphd** [comment]
Without either need to support it via Flash or http://caniuse.com/#feat=clipboard, which I'm not sure is ready for prime time yet (I might be wrong).  It looks like a dog's breakfast of impl bugs and issues.

**Comment by Pomax** [comment]
I'm not quite sure I understand; is brackets somehow preventing "native" copy/cup/paste? It feels like this is a thing that browsers already know how to do, as long as you don't intercept and kill off the event for it?

**Comment by humphd** [comment]
The context menu isn't a browser native context menu, and as such, the copy/cut/paste items produce synthetic events.  As you know, you can't really get at the clipboard without triggering native events for these.


________________________________

**Comment by Pomax** [comment]
right, so can we fake them? `new KeyboardEvent` with the control/meta key turned on, and c/x/v for the three options? The document range is native as far as I can tell, since keyboard shortcuts work, so can we just fake the keyboard shortcut directly?

**Comment by humphd** [comment]
As far as I know, you can't. These won't be trusted DOM events, which is what you need.

On Sep 26, 2015 1:59 AM, Mike Kamermans <notifications@github.com> wrote:

right, so can we fake them? new KeyboardEvent with the control/meta key turned on, and c/x/v for the three options? The document range is native as far as I can tell, since keyboard shortcuts work, so can we just fake the keyboard shortcut directly?

**Comment by Pomax** [comment]
alternative idea - since the only three options are options that don't really add value (quick edit and quick docs are easily turned into buttons instead, which would be better UX, giving the mental map for thimble stable locations for both options). Is it worth just disabling the brackets context menu in the editor (but not the file sidebar), and just letting the browser deal with right clicks?

**Comment by humphd** [comment]
I wonder if we could use https://github.com/zenorocha/clipboard.js?

**Comment by Pomax** [comment]
this looks like it's a helper utility for getting text-from-an-element into the clipboard, so we'd still need a cross-broswer range builder, to get the actual text string.

**Comment by humphd** [comment]
In #569 I reverted an [upstream commit](https://github.com/adobe/brackets/pull/12674) that added support for this via `document.execCommand()`, and fixed `cut` and `copy`, but totally broke `paste`.  They are running in a web shell vs. regular browser, so it worked for them.

It would be nice to return to this problem with fresh eyes, and a new evaluation of the various options for clipboard APIs on the web.  Maybe we can solve this in another way?

**Comment by Pomax** [comment]
I like the idea of revisiting this, do we want to close the current issue and open a new one with a ref. to this one, so we have a "Clean slate" for investigation and pontification?

**Comment by humphd** [comment]
One way we might address this is using [`document.queryCommandSupported()`](https://developer.mozilla.org/en-US/docs/Web/API/Document/queryCommandSupported) to see if the current browser will allow each of `cut, copy, paste` to work, and for each one, make a decision that either uses a `document.execCommand()` code path, or continues to ignore it and let the browser do its thing (or maybe do some *other* as-yet-unknown thing).

**Comment by Pomax** [comment]
Yeah that's the thing I ran in Chrome and Firefox to see what was supported. Someone might have already written an execCommand shim, worth looking for one?

**Comment by jgmac1106** [comment]
I commented elsewhere the way gDocs handles this is a pop up modal letting you know you need to use short cut keys to copy and paste. Not sure if a similar solution would work here.

**Comment by humphd** [comment]
For reference, what @jgmac1106 is discussing in gDocs:

![screen shot 2017-02-27 at 11 19 30 am](https://cloud.githubusercontent.com/assets/427398/23369238/acf9488e-fcde-11e6-9354-87c1706fadf9.png)

I like this idea.  My suggestion is that this bug make the following changes:

* Add back the context menu options for `cut, copy, paste` from https://github.com/adobe/brackets/pull/12674
* On startup, use `document.queryCommandSupported()` for all of `cut, copy, paste` and see which ones are actually supported in the current browser
* If something's supported, use `document.execCommand()` on it; if it's not supported, show a dialog like Google's above.

Eventually, we may never show the dialog, since `queryCommandSupported` might be true for all 3.  This would give us the best of both worlds until then.

Is this an acceptable way forward?  If so, let's get someone working on this.

cc @flukeout.

**Comment by Pomax** [comment]
ah, interesting. Yeah that sounds fine, if we can find the right place to surface this.

**Comment by mfainshtein4** [comment]
I'll give this a shot.

**Comment by humphd** [comment]
@mfainshtein4 excellent, it's yours.  I sketched out a solution above, let me know if you have more questions or need advice/help.

**Comment by mfainshtein4** [comment]
Hey, i've been unsure on how to progress and could use some help. 

I have been following the outline @humphd  posted and I remade made the changes as per adobe#12674, I checked if the browser supports the command on start up and I created the dialog boxes using the google docs one as a template as a preview you can check it out here:
https://www.w3schools.com/code/tryit.asp?filename=FDF8WFSPNI0J
so I am now at the final portion which is integrating the dialog.html with the EditorCommandHandler.js, but I am not 100% sure on how to do this. The way I was initially planning it would look like
    function _execCommand(cmd) {
        window.document.execCommand(cmd);
    }
    function _execCommandCut() {
	  if(cut)
	    _execCommand("cut");
	  else{
        showDialog();  		  
	  }
    }
where cut is the boolean if the browser supports it. So would it be possible to call showDialog(); from the js file? if so how do I "include" it?

**Comment by humphd** [comment]
Start by applying this commit to our code https://github.com/adobe/brackets/pull/12674/commits.  You can do this by doing:

```
git checkout -b issue-451
git revert 95bdac5b3838fda092990ca7ebaa96e982b33179
```

Now you'll have the same changes that are in https://github.com/adobe/brackets/pull/12674/commits/d93ccc532cc11265314036860b2863ce30469b95 applied to your `issue-451` branch.  Try running Brackets and testing cut, copy, paste by doing `npm start` and going to `http://localhost:8000/src/hosted.html` and right clicking on files.  You'll see the problem.

Next, we need to modify the code you just reverted in that commit so that it does some checks in the current browser.  In your snippet above you have `if(cut)` which should really be:

```js
// NOTE: this code is untested, it's just a guide for you
function _execCommandCut() = (function() {
  if(document.queryCommandSupported("cut")) {
    return function() {
     _execCommand("cut");
    };
  } else {
    return ignoreCommand;
  }
}());
```

You need to do something like the above for all 3 commands.

In terms of how to open a dialog, with a question like this you want to do some research in the existing code.  You know that there is a ton of code in Brackets that uses dialogs already.  So you want to see how they do what they do.

Here's an example:

https://github.com/mozilla/brackets/blob/master/src/utils/DragAndDrop.js#L73-L102

You'll see how it's included in that file in lines 31-41.

**Comment by humphd** [comment]
@mfainshtein4 here is what we did together:

```diff
diff --git a/src/base-config/keyboard.json b/src/base-config/keyboard.json
index 335236ad9..c10aa63cf 100644
--- a/src/base-config/keyboard.json
+++ b/src/base-config/keyboard.json
@@ -40,9 +40,6 @@
     "edit.copy": [
         "Ctrl-C"
     ],
-    "edit.paste": [
-        "Ctrl-V"
-    ],
     "edit.selectAll":  [
         "Ctrl-A"
     ],
diff --git a/src/command/DefaultMenus.js b/src/command/DefaultMenus.js
index a8e94bb69..b1d1c58bb 100644
--- a/src/command/DefaultMenus.js
+++ b/src/command/DefaultMenus.js
@@ -72,9 +72,9 @@ define(function (require, exports, module) {
             // Native-only - can't programmatically trigger clipboard actions from JS menus
             menu.addMenuItem(Commands.EDIT_CUT);
             menu.addMenuItem(Commands.EDIT_COPY);
-            menu.addMenuItem(Commands.EDIT_PASTE);
             menu.addMenuDivider();
         }
+
         menu.addMenuItem(Commands.EDIT_SELECT_ALL);
         menu.addMenuItem(Commands.EDIT_SELECT_LINE);
         menu.addMenuItem(Commands.EDIT_SPLIT_SEL_INTO_LINES);
@@ -254,6 +254,12 @@ define(function (require, exports, module) {
         editor_cmenu.addMenuItem(Commands.TOGGLE_QUICK_EDIT);
         editor_cmenu.addMenuItem(Commands.TOGGLE_QUICK_DOCS);
         editor_cmenu.addMenuItem(Commands.EDIT_SELECT_ALL);
+        editor_cmenu.addMenuItem(Commands.EDIT_PASTE);
+        if(document.queryCommandSupported("cut")) {
+            editor_cmenu.addMenuItem(Commands.EDIT_CUT);
+        
+        }
+
 
         var inline_editor_cmenu = Menus.registerContextMenu(Menus.ContextMenuIds.INLINE_EDITOR_MENU);
         inline_editor_cmenu.addMenuItem(Commands.TOGGLE_QUICK_EDIT);
diff --git a/src/editor/EditorCommandHandlers.js b/src/editor/EditorCommandHandlers.js
index 6e7317d0b..06457020b 100644
--- a/src/editor/EditorCommandHandlers.js
+++ b/src/editor/EditorCommandHandlers.js
@@ -1137,6 +1137,11 @@ define(function (require, exports, module) {
         return result.promise();
     }
 
+    function testPaste() {
+        console.log("paste command");
+        return (new $.Deferred()).reject().promise();
+    }
+
     // Register commands
     CommandManager.register(Strings.CMD_INDENT,                 Commands.EDIT_INDENT,                 indentText);
     CommandManager.register(Strings.CMD_UNINDENT,               Commands.EDIT_UNINDENT,               unindentText);
@@ -1157,6 +1162,6 @@ define(function (require, exports, module) {
     CommandManager.register(Strings.CMD_REDO,                   Commands.EDIT_REDO,                   handleRedo);
     CommandManager.register(Strings.CMD_CUT,                    Commands.EDIT_CUT,                    ignoreCommand);
     CommandManager.register(Strings.CMD_COPY,                   Commands.EDIT_COPY,                   ignoreCommand);
-    CommandManager.register(Strings.CMD_PASTE,                  Commands.EDIT_PASTE,                  ignoreCommand);
+    CommandManager.register(Strings.CMD_PASTE,                  Commands.EDIT_PASTE,                  testPaste);
     CommandManager.register(Strings.CMD_SELECT_ALL,             Commands.EDIT_SELECT_ALL,             _handleSelectAll);
 });
```

**Comment by mfainshtein4** [comment]
@humphd 
![current](https://cloud.githubusercontent.com/assets/11540135/24209300/3fba8cbc-0efc-11e7-9f9b-0c66a840df14.png)

This is how the work looks like a the moment. I removed cut, copy, and paste from keyboard.json as the shortcut commands are handled natively and it was causing the shortcuts to call the dialogs if the commandQuerySupported is false. Is this solution fine?

**Comment by jgmac1106** [comment]
Is it contextual? Meaning recognizing operating system so it will say Cmd+C for Mac OS users?

**Comment by mfainshtein4** [comment]
it is not. should it be? I was going by googles dialog as reference and their doesn't.

**Comment by Pomax** [comment]
it should be - windows/unix/linux use "contrlol", whereas OSX uses the apple "command" key (which is the 'meta' key corresponding to the windows key on windows, and 'a key we don't use' on unix/linux)

**Comment by mfainshtein4** [comment]
and id use navigator.platform to figure this out correct?

**Comment by Pomax** [comment]
yep. Basically if `navigator.platform.indexOf('Mac') !== -1` we know we're dealing with an OSX flavour that uses the `⌘+...` rather than `ctrl+...`

**Comment by mfainshtein4** [comment]
makes sense. Ill get cracking on that. Thanks for the feedback :)
