### ISSUE TITLE
Zip file upload size limit

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/brackets#491]
Apparently, the limit that we enforce on individual file sizes for upload (3mb) is also enforced for zip files that we expect to unzip inside the file tree i.e. I cannot upload a zip file that is > 3mb.

I don't think that this should be the case because the zip file can contain multiple < 3mb files that would be perfectly valid to upload individually. Seems like a bit of an unnecessary UX hassle to do it that way though.

**Comment by humphd** [comment]
Related, we should figure out what our upper limits are on the publish server and where things start to break down in terms of scaling.  That should likely inform this.

**Comment by MargarytaChepiga** [comment]
I would like to work on this bug!

**Comment by humphd** [comment]
@MargarytaChepiga it's yours.  I'll leave notes soon on how to fix this.

**Comment by humphd** [comment]
When a user drags-and-drops a zip file (see https://github.com/mozilla/thimble.mozilla.org/wiki/Using-Thimble#upload-archives) we run code that checks for the size of the file they are dropping:

https://github.com/mozilla/brackets/blob/master/src/utils/DragAndDrop.js#L52-L54

We then use this limit to check the size of the file when it's dropped, and reject it if it exceeds the max size:

https://github.com/mozilla/brackets/blob/master/src/utils/DragAndDrop.js#L330-L349

To fix this, we'd want to first determine if this is a `*.zip` file, based on the file's extension.  If it is, we should allow the size to be larger--I'm not sure what that max size should be, maybe 5M? 10M?
