### ISSUE TITLE
Color picker only works for an existing color

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/brackets#493]
In a css file, start typing in `color:` and then press `Cmd+E`. It tries to (unsuccessfully) open up a Quick Edit widget instead of a color picker.

Now type in `red` or some other color and now press `Cmd+E` - it opens up the color picker.

Requiring a color to already be present to enable the color picker is some pretty bad UX. Also, having a Quick Edit for CSS does not really make a lot of sense we don't really do links to files in CSS (we may want to support this with `@import` but we should special case that). 

Instead, we should always show the color picker for tags such as `color`, `background`, `background-color`, `font`, `font-color`, etc. as soon as the `:` is inserted.

**Comment by aayushsanghavi** [comment]
@gideonthomas I'd like to take this issue. How do I get started with it?

**Comment by aayushsanghavi** [comment]
@gideonthomas I was able to replicate the issue above in the thimble editor.
I did some look up. Is the issue in the [InlineColorEditor](https://github.com/mozilla/brackets/blob/master/src/extensions/default/InlineColorEditor/InlineColorEditor.js) file?

**Comment by humphd** [comment]
Likely the error is in here: https://github.com/mozilla/brackets/blob/master/src/extensions/default/InlineColorEditor/main.js#L33-L77, and I'd guess that if it can't recognize the current colour (e.g., nothing) it gives up.  We could default to something like `white` if that happens, vs `null`.

**Comment by aayushsanghavi** [comment]
@humphd thanks for the link. I read the code. I have a doubt though, when nothing matches, if we return white instead of null, won't it show the color picker on any random word even when we don't want it?

**Comment by humphd** [comment]
Yeah, the details will matter, and I'm just guessing from a quick look at the code.  These providers have to be invoked, though, so we're looking for it to be possible to use it even when there isn't a value.  Whoever does this will need to experiment with the actual UX to see what makes sense.

**Comment by gideonthomas** [comment]
@aayushsanghavi this doesn't seem like an easy bug to fix tbh. This is where it's failing: https://github.com/mozilla/brackets/blob/master/src/extensions/default/InlineColorEditor/main.js#L54. It fails because of the intrinsic behavior of this extension - it relies on providing the color editor as a "guide" once you've already started typing in a color to help refine your color choice and is not meant for providing you a color (from its picker) from scratch (at least that's what their code suggests). Out here: https://github.com/mozilla/brackets/blob/master/src/extensions/default/InlineColorEditor/main.js#L49 they use a regex that checks for colors and only then shows the color picker based on a matching regex for colors. It does not check what css property you're typing in a color for; in fact, it does not care about the css property at all. You can test this by simply typing in `red` literally anywhere in a CSS file (even if it isn't valid CSS) and pressing `Cmd+E` to show the color picker.

I think to fix it, we would need to change the intrinsic behavior of how the color picker decides whether it is in the right context or not, i.e. it should decide it based on the css property vs. a color. This means that you'd have to do some minor token parsing similar to https://github.com/mozilla/brackets/blob/master/src/extensions/default/CSSCodeHints/main.js#L250-L311 to see if what the user entered was a CSS property and that its type is `color` by relying on this file: https://github.com/mozilla/brackets/blob/master/src/extensions/default/CSSCodeHints/CSSProperties.json. Then you can show the inline color picker accordingly.

cc @humphd

**Comment by aayushsanghavi** [comment]
Thanks a lot @gideonthomas. I followed your instructions and I managed to make some progress (when any css property with type color is mentioned the color picker pops up with default color white) but the UX is not good. If you and @humphd could review my code and help me with it, it'd be great.
Also, I'm stuck with a small issue, I can't include the CSSCodeHints file. I tried
`CSSProperties = brackets.getModule("extensions/default/CSSCodeHints/text!CSSProperties")`
but that isn't working. (For now I had copied the file in the InlineColorEditor folder).

**Comment by humphd** [comment]
`CSSProperties = brackets.getModule("text!extensions/default/CSSCodeHints/text!CSSProperties.json");`

In terms of moving this forward, do a WIP (Work in Progress) PR and please include a screencast animated gif to show how it works.  You can use http://www.cockos.com/licecap/ or similar to create it, then include that in your PR's comment.  It makes it easier to discuss.

**Comment by aayushsanghavi** [comment]
@humphd thank you! I tried that but the CSSProperties include didn't work. For the gif I'll keep a copy of CSSCodeHints.json but in the PR I'll keep the include syntax you mentioned. Please help me fix that.

**Comment by gideonthomas** [comment]
@aayushsanghavi I think it's better if you just copy/paste that file into the same folder so that you can simply `require("text!CSSProperties.json")` and so that it'll be easier for us when we update with upstream Brackets.
