### ISSUE TITLE
Provide visual indication that an inline editor or quick doc view is available

### ISSUE THREAD

**Issue by humphd** [mozilla/brackets#499]
We have keyboard shortcuts for things like the inline colour picker, HTML and CSS docs, etc.  However, you have to a) know what these shortcuts are (and we don't tell you!); and b) have to know _when_ to use them (your cursor has to be placed in exactly the right spot).

I think we should provide a way for apps to signal to the user that there is some kind of helper they could use for their given cursor position.  In Thimble, for example, we might put an icon at the top that when clicked pops open the inline helper.  Or, we might choose to do this in Brackets, and put an icon to the left of the line number in the gutter.

The mechanics of making it possible are one thing, the UX another.  My _goal_ is to make it so that you can discover these features vs. just having to know.

cc @flukeout

**Comment by davidhuang1550** [comment]
I would like to take a crack at this!

**Comment by humphd** [comment]
This is going to have to be done in stages, and it won't be trivial.  The first step is going to be to make it possible to query Brackets with some API in order to determine if there is an inline editor or inline doc handler available for the current cursor position.

The `EditorManager` keeps track of all the inline editor/doc providers: https://github.com/mozilla/brackets/blob/master/src/editor/EditorManager.js#L79-L93.  And here's the code that gets called when you right-click on something and click `Quick Docs` or `Quick Edit`: https://github.com/mozilla/brackets/blob/master/src/editor/EditorManager.js#L281-L321.

So I *think* we'd want to have new code that sees if there is an inline editor or doc provider available.  The question is *when* and *how often* to call this?

**Comment by flukeout** [comment]
We could start with the colorpicker.

**Comment by humphd** [comment]
Probably it would be good to look at the use of the `cursorActivity` event on the CodeMirror editor object.  Quite a bit of the Brackets code relies on this to figure out when to show/hide tooltips, do autocomplete, etc:

https://github.com/adobe/brackets/search?utf8=%E2%9C%93&q=cursorActivity

**Comment by davidhuang1550** [comment]
@humphd so i have successfully been able to communicate with brackets from thimble, as well as sending back information seeing if there are any inline helpers available. What should the next step be?

**Comment by Pomax** [comment]
@davidhuang1550 it is a good idea to push your work-so-far up to your fork on github, and then filing a PR that has a title that starts with "[WIP]" (Work In Progress) so that everyone can comment on code that everyone can see. Even if you keep working on it, it allows for a conversation about the approach taken early on, so you don't end up working for a week only to hear "it would have been better to..." for something you did on day one =)

**Comment by davidhuang1550** [comment]
[Pull Request](https://github.com/mozilla/brackets/pull/617)
