### ISSUE TITLE
No hints when we move files

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/brackets#514]
STR:
1. create a folder called `images`
2. move an image into that folder
3. in your `index.html` file type in `<img src="` and look at the suggestions
4. The image you just moved does not show up as one of the suggestions

**Comment by humphd** [comment]
I'm pretty sure it does show up if you add the trailing `/`.  Brackets does, at least.

**Comment by gideonthomas** [comment]
Yeah I think it will show it once you type in the `images/` part. But It should probably show it as soon as it encounters the `="` no?

**Comment by humphd** [comment]
This is https://github.com/mozilla/brackets/issues/514 in Thimble.
