### ISSUE TITLE
`npm run build` fails on jshint running over localization files if run more than once

### ISSUE THREAD

**Issue by Pomax** [mozilla/brackets#559]
It looks like the locale files that are pulled in during `npm run build` are dropped in a location that is covered by the jshint task, such that when you run `npm run build` a second time, the build process gets cut off over code style errors.

Running `npm run unlocalize` to remove the locale files prior to running `npm run build` fixes this, so a build might need to either scrub those files and refetch, or the jshint task will need to be told to ignore the place(s) where we drop locale files

(tested on windows 10)

**Comment by gideonthomas** [comment]
I cannot reproduce this error on Mac. But on Windows, the following error is seen:
```
> Brackets@1.4.0-0 build ...\mozilla\brackets
> grunt build-browser

Running "jshint:src" (jshint) task
Linting src/nls/dsb/strings.js...ERROR
[L118:C75] W107: Script URL.
    "DETECTED_EXCLUSION_TITLE": "JavaScript: Problem datajoweje inference",
Linting src/nls/hsb/strings.js...ERROR
[L118:C75] W107: Script URL.
    "DETECTED_EXCLUSION_TITLE": "JavaScript: Problem datajoweje inferency",

Warning: Task "jshint:src" failed. Use --force to continue.
```

**Comment by kyasbal-1994** [comment]
I could reproduce this issue too. Is there any plan to fix this issue?

**Comment by Pomax** [comment]
probably the best solution would be to switch to a current ESLint vesion, now that it's joined forces with JSCS to be a combined linter and formatter, wich numerous fixes that improve on the old jshint parsing and reporting.

**Comment by gideonthomas** [comment]
I'll just update brackets with what's upstream, they use eslint now.

**Comment by humphd** [comment]
Is this fixed now that we have switched over to eslint?

**Comment by gideonthomas** [comment]
@Pomax are you able to confirm this? ^

**Comment by Pomax** [comment]
pretty sure it's fixed because I had to run the brackets build to make things work last week and did not run into this. sooooo closed!
