### ISSUE TITLE
Cherry Pick upstream updates

### ISSUE THREAD

**Issue by humphd** [mozilla/brackets#563]
I notice that there's been a bit of activity on Adobe's upstream, some of which we might care about: https://github.com/adobe/brackets/pulse/monthly.  It might make sense at some point to sort through the commits over the past year and figure out which ones we should take here.

**Comment by gideonthomas** [comment]
We should wait until they release v1.8 and then take in the commits.

**Comment by humphd** [comment]
1.8 has shipped https://github.com/adobe/brackets/wiki/Release-Notes:-1.8

**Comment by gideonthomas** [comment]
Will work on this on Monday

**Comment by humphd** [comment]
Dupe of #569.
