### ISSUE TITLE
DEV: Move to... option doesn't appear in right-click menu in Dev environment.

### ISSUE THREAD

**Issue by flukeout** [mozilla/brackets#583]
Even with a folder present in the file tree, it's not showing up for me...

<img src="https://cloud.githubusercontent.com/assets/25212/22804140/9ad7d352-eecc-11e6-8ccd-2466977202d4.png" width="300"/>

Anyone else? cc @gideonthomas

**Comment by gideonthomas** [comment]
Yeah. It's a localization bug. It's missing the string for "Move To" and so it doesn't run the extension.

**Comment by flukeout** [comment]
Does that mean it might not appear in prod for some locales?

**Comment by gideonthomas** [comment]
no it works fine on prod. I'm still not sure why this doesn't work locally (just know that the string that it uses, which is localized, somehow ends up being `undefined`)

**Comment by humphd** [comment]
We fixed this by always running `npm run localize` when the server starts, closing.
