### ISSUE TITLE
Update node deps

### ISSUE THREAD

**Issue by humphd** [mozilla/brackets#589]
For any node dep we have in `package.json` that is *not* also used by Adobe upstream (see https://github.com/adobe/brackets/blob/master/package.json), we should see if we can update things.  We use a lot of stuff that they don't, so it's on us to keep things updated.

**Comment by badrmodoukh** [comment]
I would like to work on this
To do this I need to check the package.json file for any missing dependencies and add the missing ones?
Is this correct?

**Comment by humphd** [comment]
@badrmodoukh OK, go for it.  You're going to need to examine the `dependenencies` and `devDependencies` in https://github.com/mozilla/brackets/blob/master/package.json and see which ones we're using that need to be updated.  You could use a tool to help you, for example https://www.npmjs.com/package/npm-check.

The one thing I want to avoid, however, is updating `dependencies/devDependencies` that Adobe uses upstream, which you can see in https://github.com/adobe/brackets/blob/master/package.json.  We should leave these alone, since they will get updated when we merge their upstream commits later.

**Comment by waseem18** [comment]
Any progress? I would like to take up this if @badrmodoukh is not working on this!

**Comment by humphd** [comment]
@waseem18 I'm pretty sure he is, based on his recent blog post.

Can I help you find another bug?  Or was this one important to your work?

**Comment by badrmodoukh** [comment]
Yes I am working on this 
Will have it finished by tomorrow

**Comment by waseem18** [comment]
@humphd can you please help me in finding another good first bug?!

**Comment by humphd** [comment]
@waseem18 for sure.  I'd suggest looking at https://github.com/mozilla/thimble.mozilla.org/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3A%22good%20first%20bug%22%20-label%3A%22assigned%20to%20contributor%22, maybe https://github.com/mozilla/thimble.mozilla.org/issues/1771 for example, if you're comfortable with JS.  Happy to help you with whatever you end up choosing.
