### ISSUE TITLE
Remove or Update issue template

### ISSUE THREAD

**Issue by humphd** [mozilla/brackets#593]
https://github.com/mozilla/brackets/blob/master/ISSUE_TEMPLATE.md got added when we merged with upstream.  We should either remove it, or modify it to fit our project.

**Comment by badrmodoukh** [comment]
I would like to work on this 
I was thinking I can add more information and change the formatting
Or I can just delete the file 
Let me know what you guys think

**Comment by humphd** [comment]
@badrmodoukh it's yours.  Let's keep this file, but modify it.  Here are my suggestions:

* Get rid of the Prerequisites section
* Keep the section on Steps to Reproduce, Expected and Actual behaviour
* Change the Versions section to be about which Browser (name and version) and OS the user is using
