### ISSUE TITLE
Consider adding filetree icons

### ISSUE THREAD

**Issue by humphd** [mozilla/brackets#599]
@flukeout I saw this extension and thought of you:

https://github.com/drewbkoch/Brackets-File-Icons

![](https://raw.githubusercontent.com/drewbkoch/Brackets-File-Icons/master/screenshots/screenshot1.jpg)

Do you like that, or are you happy with what we have now?

**Comment by flukeout** [comment]
I like the concept of icons, but I feel like this set is too vast & varied. I'll borrow some of these to make a mockup though. I think at least we could distinguish between 

* folders
* code 
* images

We could also check our DB to see what kinds of files people are using.

**Comment by humphd** [comment]
If you pick the font/images/icons to use, we can just fork this and do it.  Nothing special about the ones chosen here.

**Comment by peiying16** [comment]
Interesting. I'm working on this issue.
![image](https://cloud.githubusercontent.com/assets/25106861/24077842/f3bde6f6-0c30-11e7-97d0-3d5e15c77f62.png)
Now, I added a gif icon beside the file name. I think I need to add a function to load different gif file base on the extension name.

**Comment by peiying16** [comment]
Where can I get the icons? @humphd

**Comment by flukeout** [comment]
Hey @peiying16 - can you open a pull request for this change? I'll provide an icon there. We might need two colors of icons, or one color that works on both the dark and light themes.

**Comment by peiying16** [comment]
Yeah. Most of the codes are done. I'm testing.

**Comment by peiying16** [comment]
@flukeout PR is here https://github.com/mozilla/brackets/pull/660
