### ISSUE TITLE
`allowJavascript` preference not honored on refresh

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/brackets#606]
Regression from b524178098f17ccf129268daf4664493916835cb

While this works properly when used in Thimble because we manually update the preference on load in Thimble, Bramble on its own, although having remembered the correct value in `localStorage`, it doesn't actually reflect that setting in the editor.

STR:
- Open up Bramble in a browser
- Add `<script>alert("Hi");</script>` somewhere in the `<body>` tag of the `index.html` file and watch it pop up an alert every time you hit Enter in your editor
- Open your dev console and type in `bramble.disableJavaScript()`. Now, every time you press Enter in your editor, you won't get the alert.
- Refresh the page and the alert pops up again and every time you hit Enter in the editor, it will alert.
- Inspect localstorage for the `bramble-property::allowJavaScript` and you'll see that it is `false`. But the editor clearly does not honor that.

**Comment by humphd** [comment]
cc @peiying16, who might want to help fix this regression.

**Comment by Pomax** [comment]
Is there a way to add a test for this? Can you  even test across reloads? >_>

**Comment by peiying16** [comment]
I think it is thimble side issue.
https://github.com/peiying16/thimble.mozilla.org/blob/af0da5eeeb727d37462a75e6e38ad3f3b57baeac/public/editor/scripts/editor/js/fc/bramble-menus.js#L58-L80
When the toggle is clicked, it does 3 things.
1. Set the UI
2. Change the property value
3. disable/ enable JavaScript
However, it only sets the UI when it initials. When can call the enable/disable function when it initials.
But I'm not sure what the analytics.event() function does. Should I add it after the enable/disable function when it initials? Anyone knows what the analytics.even() does?

I would like to try fixing it.

**Comment by Pomax** [comment]
the analytics event is a Google Analytics signal to tell us how many users are toggling JS runs, so should only kick in when a user actively changes that setting, not during initialisation.

**Comment by peiying16** [comment]
OK. I got it.

**Comment by gideonthomas** [comment]
@peiying16, I don't think the issue actually lives in Thimble since I can reproduce this by just running Bramble alone (see the STR above). I think the issue is that when we load Bramble, we don't actually disable javascript when we read from `localStorage`.

**Comment by peiying16** [comment]
@gideonthomas This is one of the methods to fix. We can click on the toggle to disable/enable, so we can do the same when thimble loads bramble menus.
https://github.com/mozilla/thimble.mozilla.org/pull/1785

**Comment by peiying16** [comment]
@gideonthomas You are right. It should be fixed on brackets. Can we call bramble.disableJavaScript(), when brackets is loading.

**Comment by humphd** [comment]
Ideally you don't have to call that directly on load, we should be passing it in with the initial state data bramble gets on startup.
