### ISSUE TITLE
Expand JavaScript Console Handling

### ISSUE THREAD

**Issue by raygervais** [mozilla/brackets#631]
### Description
The bare bones of the editor console has been implemented, and needs to be expanded upon to include standard console functionality such as the following:

- [x] console.error()
- [x] console.clear()
- [x] console.assert()
- [ ] console.count()
- [x] console.info()
- [x] console.time()
- [ ] console.trace()
- [x] console.warn()

This issue extends the **[WIP]** pull request #624, which was the original implementation. Details for the console conceptualization can be found [here](https://github.com/mozilla/thimble.mozilla.org/issues/1675)

**Comment by gideonthomas** [comment]
@humphd are the above console methods meant to be implemented in that PR linked or it's fine to implement it as a separate issue?

**Comment by humphd** [comment]
Doing this in a follow-up PR is fine with me.  As long as all of those get left alone or set to `_log` in his other patch, should be good.

**Comment by raygervais** [comment]
@humphd, I've been pushing commits to the same branch, resulting in the additional console code ending up in the linked PR. All that is left is trace, count, and assert from the list above, plus any others that I may have missed. 

If you'd like me to push them to this issue, how can I ensure that Github directs them instead of the PR, to here?

**Comment by gideonthomas** [comment]
Still to be done here:
`console.trace` and `console.count`

**Comment by Pomax** [comment]
Updated the first comment to use a checkbox list so progress is automatically tracked by github

**Comment by raygervais** [comment]
@humphd @flukeout I'd like to keep expanding the console -starting with `console.count`. Should I create a new issue in Thimble's main repository so we can discuss anything that can go into Console 1.1? I promise not to disappear again 👍

**Comment by flukeout** [comment]
Hey @raygervais! Yeah I think let's start a new issue in the Thimble repo. It's easier if we just track this type of work there. Did you see the console related issue @Pomax filed...

* https://github.com/mozilla/thimble.mozilla.org/issues/2186

I think that would be good to tackle too, curious what you think about it.

**Comment by raygervais** [comment]
I agree, that issue should be tackled in V1.x (what ever you decide to call this update), and since I wrote it I think I know how to remedy the initial issue itself 👍. I do like Dave's suggestion to incorporate util-inspect if it would help for further refinement. I'll create an issue on Thimble and then someone can close this one!

**Comment by flukeout** [comment]
Sounds good!
