### ISSUE TITLE
eslint doesn't check code in src/extensions/*

### ISSUE THREAD

**Issue by humphd** [mozilla/brackets#654]
By design, Brackets doesn't run eslint on many extensions.  They did this because a lot of them were included via submodule, and were owned by other people with other code styles.

We have a number of extensions that live in our tree, and we manage all the code directly in this repo.  We should be linting these.  We actually used to do it, but when we merged with upstream, they changed to eslint from jshint, and altered the way that it sets which files to lint.

The fix for this is to add the following directories to the `eslint:src` definition:

* `src/extensions/default/Autosave`
* `src/extensions/default/BrambleUrlCodeHints`
* `src/extensions/default/UploadFiles`
* `src/extensions/default/bramble-move-file`
* `src/extensions/default/bramble`
* `src/extensions/extra/SVGasXML`
* `src/extensions/extra/HTMLHinter`
* `src/extensions/extra/MDNDocs`
* `src/extensions/extra/bramble-watch-index.html`

The [Gruntfile](https://github.com/mozilla/brackets/blob/master/Gruntfile.js) is where you need to work, see https://github.com/mozilla/brackets/blob/master/Gruntfile.js#L403-L410.

@gideonthomas did I miss any that you can think of?

**Comment by Blackweda** [comment]
I'll fix it up.

**Comment by humphd** [comment]
Thanks, @Blackweda, it's yours.

**Comment by Blackweda** [comment]
so I added the necessary code.. quick question, Is **'<%= meta.src %>',** still necessary? For now I actually commented it out but left it in the code.

**Comment by Blackweda** [comment]
I made a PR. Let me know if changes are in order.

**Comment by humphd** [comment]
This was fixed through subsequent patches, closing.
