### ISSUE TITLE
Cannot find module 'sw-precache' when installing brackets

### ISSUE THREAD

**Issue by ryanwarsaw** [mozilla/brackets#657]
When I run the command ```npm install``` to install the dependencies for brackets, eventually I'll be led to the post-install task ```grunt install``` where I'll be greeted with an error originating from the ```Gruntfile.js``` claiming it can't find the module ```sw-precache```.

This has only started happening recently, my previous clone of brackets didn't have this issue. I created a new clone while debugging a contributors issue, and this error occurred. If I manually install the dependency the error goes away and all is well again.

https://gist.github.com/ryanwarsaw/fbcfbd76a11da550be3e7611fb7e2a16#file-gistfile1-txt-L121

Filing this just to make sure it's documented, I may look into it further at a later date.

**Comment by humphd** [comment]
This is odd.  We define `sw-precache` in `package.json`, but it's a `devDependency`.  According to http://stackoverflow.com/questions/34700610/npm-install-wont-install-devdependencies?answertab=active#tab-top, if your `NODE_ENV` is set to `production` it won't install it.  Are you setting it by chance?

**Comment by ryanwarsaw** [comment]
Yep, good catch! I had remnants of another bug I had been trying to look into, which involved me setting NODE_ENV to production.
