### ISSUE TITLE
'npm install' is missing some dependencies

### ISSUE THREAD

**Issue by nailaandleeb** [mozilla/brackets#662]
I have cloned the latest version tomorrow and run according to the instructions.'npm install' and 'npm run build'.but this is skipping thirdparty modules like ."https://github.com/mozilla/brackets/tree/master/src/thirdparty" ....I had to install them manually.
.
I am running this at <a href="http://c9.io/">Cloud9</a> environment.

**Comment by ryanwarsaw** [comment]
You need to initialize github sub-modules, you can do this by appending the ```--recursive``` flag to your clone command, or if that isn't available you can do ```git submodule update --init --recursive```.
