### ISSUE TITLE
Dragging some file types into browser fails silently (e.g., .txt)

### ISSUE THREAD

**Issue by humphd** [mozilla/brackets#668]
From https://github.com/mozilla/brackets/pull/659#issuecomment-289606811, we seem to silently fail to import certain file types when dragging-and-dropping

STR: 

* create a file on your desktop `text.txt`
* drag it from the desktop into the filetree
* note that the file is not created, no errors on the console
* rename the desktop `text.txt` to `text.js`
* drag it from the desktop into the filetree
* note that the file is now created

**Comment by ZenanZha** [comment]
@humphd I'm not be able to reproduce the bug. This might be fixed somehow.

**Comment by ZenanZha** [comment]
@humphd I'll wait for the merging of this pull: [.](https://github.com/mozilla/brackets/pull/659)
Then I could work on this issue. I will start form this branch: [humphd:dnd-folders](https://github.com/humphd/brackets/tree/dnd-folders)

**Comment by humphd** [comment]
@ZenanZha please don't wait, pull my branch and start figuring it out now:

```bash
$ git remote add humphd git@github.com:humphd/brackets.git
$ git fetch humphd
$ git checkout -b issue668 humphd/dnd-folders
```

Now you can start fixing the bug, doing commits, etc.  When my PR gets merged, you can do this:

```bash
$ git remote add upstream git@github.com:mozilla/brackets.git
$ git checkout master
$ git pull upstream master
$ git checkout issue668
$ git rebase master
```

**Comment by ZenanZha** [comment]
Hello professor @humphd ,
I went through those code last weekend. There are lots of code and I think I need some tips to help me start my work. Could you please help me go though these code a little bit?

**Comment by humphd** [comment]
The problem is likely in https://github.com/humphd/brackets/blob/c238c04afb107946ecabf8347c4b1e14e709fb3c/src/filesystem/impls/filer/lib/LegacyFileImport.js#L126-L145 and/or https://github.com/humphd/brackets/blob/c238c04afb107946ecabf8347c4b1e14e709fb3c/src/filesystem/impls/filer/lib/LegacyFileImport.js#L126-L145 (these two functions are similar but slightly different, depending on what the browser supports).

**Comment by ZenanZha** [comment]
@humphd 
Hello, professor.
My code is ready to go, but I cannot find the place to push it.
I would like to keep working for this bug, but I changed my 0.4 release to another one.
(becuse it seems I have no way to create a pull request base on this bug before due date.)

**Comment by humphd** [comment]
Where is your code?  At least put it somewhere I can see, even if you can't do a PR.

**Comment by ZenanZha** [comment]
Pushed on to my fork: [ZenanZha/Issue668](https://github.com/ZenanZha/brackets/tree/Issue668).
@humphd

**Comment by ZenanZha** [comment]
I only change the code on [WebKitFileImport.js](https://github.com/ZenanZha/brackets/blob/Issue668/src/filesystem/impls/filer/lib/WebKitFileImport.js) because https://github.com/humphd/brackets/blob/c238c04afb107946ecabf8347c4b1e14e709fb3c/src/filesystem/impls/filer/lib/LegacyFileImport.js#L126-L145 actually has no error.
