### ISSUE TITLE
Cancelling a file upload will not allow you to re-open the upload files dialog

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/brackets#673]
This is a bug introduced by the way we approached https://github.com/mozilla/brackets/pull/621. 

Specifically, this is the bug: https://github.com/mozilla/brackets/pull/621#issuecomment-286286626

With the same approach that that PR takes, what we really need to do is to listen for the "cancel" event on the `<input type-"file">`, but apparently that is impossible (after doing some research).

The right solution but just be to change our approach of how we handle the closing/opening logic of the dialog but we still need to figure that out.

**Comment by Pomax** [comment]
I might not understand, but why can we not "always clean up" when someone picks the upload option? We don't really need to listen for a cancel, our UI just needs to make sure that when a user takes an action that opens file-upload-UI, it makes that happen. If an old upload instance can get in the way, then the solution would appear to be to destroy it at the time it would become a problem

**Comment by Shank09** [comment]
@Pomax 
is this what you are saying?
[UploadFilesDialog.js#L143](https://github.com/mozilla/brackets/blob/master/src/extensions/default/UploadFiles/UploadFilesDialog.js#L143)
Replacing `.hide()` with `.destroy()`?

If so, destroying the `file-upload-UI` when they choose upload from computer, causes it to not upload any file.

**Comment by Pomax** [comment]
Yes: if we're hiding it already anyway and it doesn't come back on a file selection, then we might as well destroy it immediately so that the next time a user clicks "upload", a completely new manager is created.

**Comment by Shank09** [comment]
@gideonthomas @Pomax 

We cannot call `destroy()` because it contains `this.fileInput.remove();` and it ignores the uploaded file.
However, If we call `_uploadDialog = null;` after [UploadFilesDialog.js#L143](https://github.com/mozilla/brackets/blob/master/src/extensions/default/UploadFiles/UploadFilesDialog.js#L143) every thing is working fine. It fixes this issue.

Is this good to go? If so I'll create a PR.

**Comment by Pomax** [comment]
Absolutely, if that fixes the issue, file a PR and we can test to verify!
