### ISSUE TITLE
Consider enabling InlineTimingFunctionEditor

### ISSUE THREAD

**Issue by humphd** [mozilla/brackets#681]
Brackets has an extension for graphically editing bezier curves to do easing and timing functions, similar to how the inline color editor works:

![](http://corlan.org/wp-content/uploads/2013/11/33br-3.png)

We should consider whether or not to enable it by default.  @Pomax?

If we do add it, we need to convert its LESS file to a CSS file (we try not to have extensions render LESS in the browser on startup, because it's slow).

The extension lives at https://github.com/mozilla/brackets/tree/master/src/extensions/default/InlineTimingFunctionEditor

**Comment by Pomax** [comment]
I think that without something that also shows off "what it does" as you manipulate the curve, this isn't super useful, but maybe @flukeout (who uses timing functions more than I do) has a different opinion here

**Comment by humphd** [comment]
I tend to agree.  I think this is pretty hard to imagine being generally useful.  @flukeout, please set us straight.

**Comment by flukeout** [comment]
While I do use UI like this sometimes elsewhere on the web and then copy the output to my code, it do so very rarely and doubt a beginner would benefit very much from it. Let's not include it.

**Comment by humphd** [comment]
OK, thanks, closing.  We can always add it later if we decide we need it.
