### ISSUE TITLE
Minify CSS files in dist/

### ISSUE THREAD

**Issue by humphd** [mozilla/brackets#683]
Our Gruntfile should use LESS to minify all CSS files in `dist/`, especially those in extension dirs.  Because we copy them over, we can do it in place and replace the existing unminified files.

**Comment by Pomax** [comment]
should this include CSS map generation?

**Comment by humphd** [comment]
I want to use what I did in https://github.com/mozilla/brackets/pull/690 to also combine all CSS/LESS into one file with Brackets for extensions.
