### ISSUE TITLE
Remove Working Set View code

### ISSUE THREAD

**Issue by humphd** [mozilla/brackets#692]
Brackets uses a two-part filetree, with the bottom portion being the view of all files in a project, and the upper portion being the working set view.  This latter UI shows all open files, and much of the selection code assumes you're going to want to see the current file by looking there vs. in the project view.

In Bramble, we hide the working set view, and instead choose to always show the entire project.  This has caused some bugs, for example #368.  It would probably make more sense to rip this code out completely instead of just hiding it.

In https://github.com/mozilla/brackets/pull/688 I'm suggesting this as a follow-up to the focus hack we're doing there.

**Comment by Th30** [comment]
@humphd I actually will like to continue contributing to this along side my release 0.4 (or if time contraints make this my release 0.4) I really feel like I've invested a lot of time in this, and I would like to continue if possible:)

**Comment by humphd** [comment]
Sounds good, @Th30.  It will require a bit of surgery, but shouldn't be too bad.  Probably it would be smart if we sat down together in person and made a plan.

**Comment by Th30** [comment]
@humphd that would be appreciated! I'll email you later tonight to remind and inquire about a good time!

**Comment by humphd** [comment]
I was working on some other code today, and had to touch this code a lot.  I think removing it is going to be very, very tricky, and likely not worth the trouble.  I'm going going to close this.  @Th30 can you pick another bug?  I don't want you to struggle with something this hard for so little pay off.
