### ISSUE TITLE
poststart script not running

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/brackets#723]
We expected the `poststart` script to cleanup the localization changes made in the file tree when you terminate the `npm start` script. Turns out this is not the case and it never runs.

I think we have two options:
1. Listen for SIGINT and run the cleanup code via a node script
2. Use pm2 to manage the process and let it run the cleanup code

**Comment by humphd** [comment]
Third option: combine the `start` and `poststart` into `start` like we previously did in https://github.com/mozilla/brackets/pull/680 before you had him split out.  It was working fine.  I'd do the simple thing here vs. over engineering it.

cc @dangkhue27

**Comment by gideonthomas** [comment]
@humphd that doesn't work either! My guess is that it might be OS based and it doesn't work on Mac (not sure about Linux) but does on Windows.

**Comment by dangkhue27** [comment]
It looks like if you update `npm` to version 4.5.0 then it should work.

**Comment by humphd** [comment]
Having to update `npm` seems like it isn't an ideal fix here.

**Comment by gideonthomas** [comment]
@dangkhue27 I think I'll take this issue on since it is a bit complex and requires some experimenting with (and I realized that as I was typing out my comment explaining how to fix this, I was basically writing all the code).
