### ISSUE TITLE
Refreshing FileSystemCache blob urls does not work for linked CSS files

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/brackets#751]
The title might not be right but here is some background:

This was noticed when implementing the image filters (https://github.com/mozilla/brackets/pull/694).

The project that can be used to test this is: 
[image-project.zip](https://github.com/mozilla/brackets/files/988096/image-project.zip)

STR:
- Drag and drop the project's contents into your editor. Keep the `index.html` file open in the preview.
- Switch to the `buster.jpg` file and apply a filter and hit "Apply".
- Look at the preview. Watch the second image (which is an `<img>` tag with that image) change to show the filter. Also notice the first image (which is a `div` with a `background-image` property using that image) break and not show anything.

The reason that the first image breaks is because it is still referring to the old blob url of the image before the filter was applied.

After some debugging, here are my findings:
- After saving the filtered image, we call `FileSystemCache.refresh` to refresh the blob url for the image in the cache. Then, we call `LiveDevMultiBrowser.reload` to reload the preview hoping that it will trigger a rewrite of the CSS to use the new blob url for the image. Looks like that doesn't happen.
- `FileSystemCache.refresh` doesn't change the blob url of the CSS file according to https://github.com/mozilla/brackets/blob/master/src/filesystem/impls/filer/FileSystemCache.js#L26-L30
- The `LiveDevMultiBrowser.reload` function eventually calls https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/nohost/HTMLServer.js#L136 which finds that a CSS file is linked in `index.html` and hence calls https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/nohost/HTMLServer.js#L116-L134 to get a blob url for `style.css` and replace it in the HTML. However, https://github.com/mozilla/brackets/blob/master/src/extensions/default/bramble/nohost/HTMLServer.js#L120 returns the old blob url for the CSS file (note above that the blob url for the CSS file does not change) and hence, the `if` check that follows evaluates to `true` and that same old blob url is used instead of rewriting the CSS file and generating a new blob url. That is why it breaks.

Chances are I probably used the wrong method of reloading the preview, but I'm not sure.

cc @humphd

**Comment by humphd** [comment]
I think this is the same bug we have when images aren't available if you have them selected when you first start the app.  When I was doing the SW live dev patch, I fixed that.  I can't remember all the details, but I might be able to back-port just that fix.  I need to look at what I did in #725.

**Comment by humphd** [comment]
No, I think what you're describing above is more than what I fixed, after re-reading.

**Comment by flukeout** [comment]
Is this issue I'm having related: https://github.com/mozilla/thimble.mozilla.org/issues/2205
