### ISSUE TITLE
Missing submodule for gh-pages build

### ISSUE THREAD

**Issue by humphd** [mozilla/brackets#788]
I was going to try and enable gh-pages builds for Brackets, but I notice this:

![screen shot 2017-06-06 at 9 11 27 pm](https://user-images.githubusercontent.com/427398/26857998-cc8151c6-4afc-11e7-8bc5-732f734c9665.png)

Not sure what this is, my `.gitmodules` includes:

```
[submodule "src/bramble/thirdparty/EventEmitter"]
	path = src/bramble/thirdparty/EventEmitter
	url = https://github.com/Wolfy87/EventEmitter.git
```

@gideonthomas, any ideas?

**Comment by gideonthomas** [comment]
my guess is that it's complaining because the org/user name for that repo was renamed. Try changing it to https://github.com/Olical/EventEmitter.git
