### ISSUE TITLE
incorrect upperlimit in imageresizer

### ISSUE THREAD

**Issue by arush0311** [mozilla/brackets#863]
in https://github.com/mozilla/brackets/blob/master/src/filesystem/impls/filer/lib/ImageResizer.js#L72

the upper limit is incorrect. it should be `Target_size*1.5`

**Comment by humphd** [comment]
@Pomax ^^ can you take a look at this please?

**Comment by Pomax** [comment]
it's true - the code comment is correctly describing we need `3 * target_size / 2`, but we're computing `2 * targetsize / 3` instead.

**Comment by humphd** [comment]
@arush0311 I wanted to say thanks for taking the time to track this down and file such a useful bug.  We really appreciate it.  If you want to bring your talents to Brackets/Thimble again, we'd love to have you hack with us.

**Comment by arush0311** [comment]
Hey! sorry the credit goes to @pomax. i was just trying to understand the why and he noticed it.
