### ISSUE TITLE
Remove adobe guideline when creating an issue

### ISSUE THREAD

**Issue by ericschv** [mozilla/brackets#905]
Whenever an individual wants to file an issue, the comment section displays the following guidelines that were inherited from adobe/brackets:
```
### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Versions

Please include the browser name and version you are using.
Please include the OS (macOS, Windows, Linux) you are using and the version of the OS you're running.
```
  
If they are not being followed then perhaps they can be removed.

**Comment by gideonthomas** [comment]
Thanks for filing this @ericschv! I think I might deal with this at the administrator level and disable issues for this repo entirely (after migrating the few issues we still need over to Thimble). This will probably solve some of the confusion around "where to file a Thimble ticket" as well.

**Comment by shikhar-scs** [comment]
@gideonthomas as a side measure shall I remove this format and put something else in place, something which the organisation might prefer ?

**Comment by gideonthomas** [comment]
@shikhar-scs can you modify the template to be just:
```
We track our issues in the Thimble repository. 
Please file an issue by going to this link -  https://github.com/mozilla/thimble.mozilla.org/issues/new
```

**Comment by shikhar-scs** [comment]
@gideonthomas Sure, I'll do that exactly

**Comment by shikhar-scs** [comment]
@gideonthomas I've filed a related PR, please review it
